//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HudsonLedSygnalizer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HudsonLedSygnalizerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HudsonLedSygnalizerSettings defaultInstance = ((HudsonLedSygnalizerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HudsonLedSygnalizerSettings())));
        
        public static HudsonLedSygnalizerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ci1:8282/")]
        public string HudsonUrl {
            get {
                return ((string)(this["HudsonUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hudsonWatcher")]
        public string HudsonUserName {
            get {
                return ((string)(this["HudsonUserName"]));
            }
            set {
                this["HudsonUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D0kt0r")]
        public string HudsonUserPassword {
            get {
                return ((string)(this["HudsonUserPassword"]));
            }
            set {
                this["HudsonUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int MainInterval {
            get {
                return ((int)(this["MainInterval"]));
            }
            set {
                this["MainInterval"] = value;
            }
        }
    }
}
